### PR TITLE
LRCI-635,649 Generate ci:test:stable github comment within ci:test:relevant|Include stable implicitly in relevant

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-635
https://issues.liferay.com/browse/LRCI-649

Please review my changes in this pull request and retest

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
@pyoo47
I'll resend the pull request with expected message regenerated after finish testing the changes.

**Comment by yichenroy** [comment]
Pull request resent here:
https://github.com/pyoo47/liferay-portal/pull/1130

**Pull request closed without merging**
