### PR TITLE
LRCI-795 Check build profile

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test:relevant:norebase

**Comment by yichenroy** [comment]
The result looks weird, might be due to running it with `norebase`

I opened another pr here with merge conflicts resolved to test dxp: 
https://github.com/yichenroy/liferay-portal/pull/229

**Pull request closed without merging**
