### PR TITLE
LRQA-45288 Simple compile failure

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-45288

### CODE REVIEW

**Comment by jpince** [comment]
@michaelhashimoto @yichenroy got an email notification for this failure and thought "who in the world makes a typo like `Syssstem`????" :rofl:

**Comment by jpince** [comment]
also, nj on the auto-close :)

**Comment by michaelhashimoto** [comment]
@jpince - Sorry.. this is just a test. hahah

**Comment by michaelhashimoto** [comment]
ci:reopen

**Pull request closed without merging**
