### PR TITLE
LRCI-1922 Add support for QA Website test imports in Spira

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1922

@brianchandotcom - If this looks okay, can we get new jars for the following:
* com.liferay.jenkins.results.parser
* com.liferay.poshi.core
* com.liferay.poshi.runner

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:forward

**Pull request closed without merging**
