### PR TITLE
 LRCI-1434 Add util class to reduce Testray result file size

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1434

Tested with a 100 MB Testray result file on a test-5-1 Docker VM, no issues found.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
@pyoo47 
I found some minor issues with the change, will fix and resend.

**Comment by yichenroy** [comment]
Made minor fixes and re-pushed to Peter here:
https://github.com/pyoo47/liferay-portal/pull/1362

**Pull request closed without merging**
