### PR TITLE
LPS-100926 Skip proxy setup for tomcat modules integration tests

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-100926

### CODE REVIEW

**Comment by austinchiang** [comment]
cc @4lejandrito  @michaelhashimoto

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See my comment on https://github.com/4lejandrito/liferay-portal/pull/328. The refresh token seems to be null.

**Comment by austinchiang** [comment]
I'll keep this pull open and will run the test suite again once https://issues.liferay.com/browse/LRCI-640 is merged

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by austinchiang** [comment]
ci:test:onlineediting

**Comment by yichenroy** [comment]
This turns proxy off for all existing modules integration tests which Shuyang said should be avoided: https://github.com/yichenroy/liferay-portal/pull/170/commits/ce09ce26625850c3d7061a8d4af3c8b81ff50abf

I applied Hashi's workaround and sent to Austin here, please see pull request comment:
https://github.com/austinchiang/liferay-portal/pull/513

**Pull request closed without merging**
