### PR TITLE
LRCI-699 TEST sem ver & functional dxp profile

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-699

### CODE REVIEW

**Comment by yichenroy** [comment]
@petershin I think the original `profile-dxp` issues with semantic versioning are resolved, can you verify if the current semantic versioning failure are related/unrelated to `profile-dxp`?

**Comment by petershin** [comment]
@yichenroy - Yes, they look like real failures.  I'll send you a pull on top of these changes so the test passes

**Comment by petershin** [comment]
Sent a fix for the semver issue: https://github.com/yichenroy/liferay-portal/pull/193

There'll still be a semver failure for `portal-kernel`, but I think that just involves updating the older branches

**Comment by yichenroy** [comment]
Testing here: https://github.com/yichenroy/liferay-portal/pull/194

**Pull request closed without merging**
