### PR TITLE
LRCI-1327 Use build profile to get batch name properties in portal release job

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1327

Tested here:
`dxp` test-portal-release: https://test-5-1.liferay.com/job/test-portal-release/403/consoleFull
`portal` test-portal-release: https://test-5-1.liferay.com/job/test-portal-release/402/consoleFull
`relevant` pullrequest: https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/3428/consoleFull

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Aborted the relevant test.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
@pyoo47 I think we're good to forward if `relevant` passes, tested the jar produced from this pull request:
(top level jobs only)
`dxp` test-portal-release: https://test-5-1.liferay.com/job/test-portal-release/403/consoleFull
`portal` test-portal-release: https://test-5-1.liferay.com/job/test-portal-release/402/consoleFull
`relevant` pullrequest: https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/3428/consoleFull

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:forward

cc @pyoo47 fyi I updated the initial pull request comment for forwarding purposes.

**Pull request closed without merging**
