### PR TITLE
LRCI-795 TEST CE master

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-795

@petershin
Testing master with `portal` profile in this pr

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by petershin** [comment]
@yichenroy - I see the `lpkg` failure.  I'll add another patch tomorrow morning

**Comment by petershin** [comment]
@yichenroy - Chas is taking a look at the `lpkg` tests.  He'll send a follow up pull to you: https://github.com/CAustin582/liferay-portal/pull/35

**Comment by yichenroy** [comment]
@petershin got it, thank you!

**Pull request closed without merging**
